Name=str(input("enter the name"))
Age=int(input("enter the age"))
Address1=str(input("enter the address1"))
Address2=str(input("enter the address2"))
Email=str(input("enter the email"))
Mobile=int(input("enter the Mobile no"))

print("--------------------------------------------------------------------------")
print("\t\t\t Student Information")
print("--------------------------------------------------------------------------")
print("\t\t\t Name   :",Name)
print("\t\t\t age    :",Age)
print("\t\t\t Address:",Address1)
print("\t\t\t         ",Address2)             
print("\t\t\t Email  :",Email)
print("\t\t\t Mobile :",Mobile)
print("--------------------------------------------------------------------------")
